version: "3.8"

services:
  db:
    image: postgres:15
    container_name: nextjs_prisma_board_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nextjs_prisma_board
    ports:
      - "5455:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
